// Code generated by SdkContractGenerator. DO NOT EDIT.

export const contract = {
  "create-audio": {
    "models": [
      "gemini-omni-audio"
    ],
    "fields_by_model": {
      "gemini-omni-audio": {
        "audio_id": {
          "required": true
        },
        "name": {
          "required": true
        }
      }
    }
  },
  "create-character": {
    "models": [
      "gemini-omni-character"
    ],
    "fields_by_model": {
      "gemini-omni-character": {
        "descriptions": {
          "required": true
        },
        "reference_image_url": {
          "required": true
        }
      }
    }
  },
  "text-to-video": {
    "models": [
      "gemini-omni-text-to-video"
    ],
    "fields_by_model": {
      "gemini-omni-text-to-video": {
        "aspect_ratio": {
          "enum": [
            "16:9",
            "9:16"
          ]
        },
        "duration_seconds": {
          "enum": [
            4,
            6,
            8,
            10
          ],
          "required": true,
          "type": "integer"
        },
        "output_resolution": {
          "enum": [
            "720p",
            "1080p",
            "4k"
          ]
        },
        "prompt": {
          "required": true
        },
        "seed": {
          "type": "integer"
        }
      }
    }
  }
} as const;
