# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "create-audio": {
        "models": ["gemini-omni-audio"],
        "fields_by_model": {
            "gemini-omni-audio": {
                "audio_id": {
                    "required": True
                },
                "name": {
                    "required": True
                }
            }
        }
    },
    "create-character": {
        "models": ["gemini-omni-character"],
        "fields_by_model": {
            "gemini-omni-character": {
                "descriptions": {
                    "required": True
                },
                "reference_image_url": {
                    "required": True
                }
            }
        }
    },
    "text-to-video": {
        "models": ["gemini-omni-text-to-video"],
        "fields_by_model": {
            "gemini-omni-text-to-video": {
                "aspect_ratio": {
                    "enum": ["16:9", "9:16"]
                },
                "duration_seconds": {
                    "enum": [4, 6, 8, 10],
                    "required": True,
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["720p", "1080p", "4k"]
                },
                "prompt": {
                    "required": True
                },
                "seed": {
                    "type": "integer"
                }
            }
        }
    }
}
